### PR TITLE
Modifications for IPMI

### PR DESCRIPTION
**Pull request by jcpowermac**
Changed JSON.parse to symbolize the keys
Added in docker-entrypoint.sh the ipmitool option

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Tested in lab. :+1:

**Comment by tjmcs** [comment]
just want to double-check...this was just an undetected bug in the existing code, not something we're changing to just fix what we're doing, right?

**Comment by jcpowermac** [comment]
@tjmcs yeah this was a bug.  The connect method option for ipmi requires the key be a symbol.  The changes fix that.

**Comment by tjmcs** [comment]
merged, thx for the bug fix @jcpowermac and @mtnbikenc :)

**Comment by tjmcs** [comment]
and the Docker container has been successfully rebuilt

**Pull request merged**
