### PR TITLE
added persistence json support to close #309

### LINKED ISSUE #309: Local KV Store
In order to target running hanlon on embedded devices such as android, I'd like to remove the dependency on external processes for the KV store.

### PR DESCRIPTION
**Pull request by hh**
Added persist_path to hanlon config, so we could store the data somewhere, defaults to right along side ./image

### CODE REVIEW

**Comment by hh** [comment]
```
# tree data 
data
├── images
│   ├── 4hPfy8cGTbAmJ11LkaMSvg.json
│   └── z9K4ZrI4zr3g9BYq4Fi48.json
├── node
│   ├── 3LEQxTDKZNw4wPsqrSdQVc.json
│   ├── 47V232KtV6D2ddggB0CXmK.json
│   ├── 5x7O24WHmUY6EkGdPZD61w.json
│   └── 6DZtpVffMIVtFNjzSv2Lai.json
└── tag
    ├── 608QV9LxPCB3VA3cOh9uJM.json
    ├── 60ANETnI8WHFNxchy3zgBU.json
    ├── 60BPGEsbZhwTtHHorYVG4u.json
    ├── 60CDEVJqdfjuxx0qMsUlhY.json
    ├── 60D9zskljpu3C7SHp6QxuC.json
    ├── 60F3y5RBDywyGNQYPypO4O.json
    ├── 60FMqVv4ePbDMFUvYzOoH2.json
    ├── 60JNWvfWjqIX6kTQ9ZPF60.json
    ├── 60KfNyfBhWiBUTZrH5zgcK.json
    ├── 60LxR2Cb6Ngs8nqUfv29f6.json
    ├── 60My6It2Agx1lKbM2HVPyq.json
    └── 60Nydqw3og8NDBkevoG5tI.json

```

**Comment by hh** [comment]
It's nice to be able to drop files into ./data/* and it just work. (Only loads them at the beginning, and writes when updates occur)

**Comment by jcpowermac** [comment]
Reviewed and tested, :+1:  for me, but might need to be re-based.

**Comment by tjmcs** [comment]
thx, @hh; :+1: for a merge from me now that we've got things updated...will merge shortly

**Pull request merged**
