### PR TITLE
Fixing version number in DockerFile and hanlon.gemspec

### PR DESCRIPTION
**Pull request by tjmcs**
These two files each contain a Hanlon version that should have been updated prior to yesterday's release; this PR updates these two files to reflect the new version number.

### CODE REVIEW

**Comment by jcpowermac** [comment]
Nothing major here except version changes :+1:

**Comment by mtnbikenc** [comment]
Check the date in hanlon.gemspec line 4. ;)

**Comment by mtnbikenc** [comment]
Looks good. :+1:

**Comment by tjmcs** [comment]
merging now...two thumbs up...thx @mtnbikenc and @jcpowermac

**Pull request merged**
