### PR TITLE
Quoted text in echo lines to keep metachar from breaking script

### PR DESCRIPTION
**Pull request by hickey**
Found that if certain shell metacharacters are used in the description of the model description, the os_complete script will break on the second line and not process the entire file. This patch quotes all the echo lines in all the os_complete.erb files for current OSes.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@hickey Thanks for the PR, looks like a good change.  Is there a reason for the file mode change to 755?

**Comment by hickey** [comment]
Ah, no reason. Sorry that I missed that when I committed them. Maybe Textmate thought it should have been executable. I will update the perms and provide a quick update. Thanks for catching this.

**Comment by mtnbikenc** [comment]
Looks good 👍

**Comment by jcpowermac** [comment]
lgtm 👍

**Pull request merged**
