### PR TITLE
Added models for major Ubuntu versions

### PR DESCRIPTION
**Pull request by hickey**
Here are the files to create the models for newer Ubuntu versions. 

Starting with Ubuntu 12.10 (Quantal), the net boot process changed a bit. This added a line to the preseed file to pull in an image of the base filesystem and this process has continued through all the current versions. It is expected to remain the same the 16.04 (Xenial) when it is released. 

I have included models for all major versions (13.04, 14.04, 15.04, 16.04) and 12.10 (since this is the version that changes how net booting worked).

### CODE REVIEW

**Comment by jcpowermac** [comment]
@hickey Thanks for your contribution...this was on my todo list at some point.

It might be into tomorrow (4/12) before I can test this.  

If you haven't yet done this you will need to sign the CLA.  The link is under "Submitting Changes" section of [CONTRIBUTING](https://github.com/csc/Hanlon/blob/master/CONTRIBUTING.md)

**Comment by hickey** [comment]
Yes, I read through most the CONTRIBUTING document a week or two ago to understand most of the process. I have also just gone up and signed the CLA.

**Comment by jcpowermac** [comment]
@hickey the models (xenial, quantal, trusty) that I tested have errors.  

```
 ⚡ root@hanlon-mk1  /opt/hanlon/image  docker exec hanlon_server_1 ./cli/hanlon model add -t ubuntu_quantal -l trusty -i 6r50TFK8B0vF2B6JY0Smm4 
--- Building Model (ubuntu_quantal): 
Please enter node hostname prefix (will append node number) (example: node) 
default: node
(QUIT to cancel)
 > [model] [add_model] <-undefined method `strip' for nil:NilClass

Command help:
hanlon model add (options...)
    -t, --template MODEL_TEMPLATE            The model template to use for the new model. 
    -l, --label MODEL_LABEL                  The label to use for the new model. 
    -i, --image-uuid IMAGE_UUID              The image UUID to use for the new model. 
    -o, --option YAML_FILE                   Use optional yaml file to create model 
    -h, --help                               Display this screen.
```

**Comment by hickey** [comment]
Are you testing on a develop branch? It appears from your output that you are attempting to take the defaults when you receive the error. I just did the same thing and here is my output. 

````
0:0 ᐅ hanlon model add -t ubuntu_quantal -l trusty -i 4Sap  
--- Building Model (ubuntu_quantal):

Please enter node hostname prefix (will append node number) (example: node)
default: node
(QUIT to cancel)
 >
Please enter local domain name (will be used in /etc/hosts file) (example: example.com)
default: localdomain
(QUIT to cancel)
 >
Please enter root password (> 8 characters) (example: P@ssword!)
default: test1234
(QUIT to cancel)
 >
Model Created:
 Label =>  trusty
 Template =>  linux_deploy
 Description =>  Ubuntu Quantal (12.10) Model
 UUID =>  EGs8ylXeisty0dw63yheN
 Image UUID =>  4SapirRmoxLWOFGpm3lEHr
````
Everything that I have been working on has been the latest master branch from 4 weeks ago (git commit id: 7b7cfbe). Here is the layout of the tree that I have on my side. 

````
* 705600d - (2 seconds ago) Fixed Ubuntu preseed files after changing filesystem.squashfs URL (HEAD, running)
* 8e776cf - (2 seconds ago) Added Ubuntu version numbers to existing models
* 2e707e4 - (2 seconds ago) Added models for major Ubuntu versions
* 8816941 - (2 seconds ago) Fixed additional references to puppet scripts
* 107f88b - (2 seconds ago) Added salt broker to included brokers
* 52dbd8b - (2 seconds ago) Created salt broker plugin
* 1ef5c19 - (2 seconds ago) Added tags for number of disks, volumes and cpu cores
* 33e2ba9 - (3 weeks ago) Added OS version to image list output (origin/feature/cli-enhancements, feature/cli-enhancements)
| * 1658695 - (6 minutes ago) Added tags for number of disks, volumes and cpu cores (origin/feature/system_tags, feature/system_tags)
|/
| * e9d2b83 - (11 minutes ago) Fixed additional references to puppet scripts (origin/feature/salt_plugin, feature/salt_plugin)
| * 968b112 - (3 weeks ago) Added salt broker to included brokers
| * 343a1e5 - (4 weeks ago) Created salt broker plugin
|/
| * f26e497 - (4 days ago) Fixed Ubuntu preseed files after changing filesystem.squashfs URL (origin/feature/ubuntu_releases, feature/ubuntu_releases)
| * 0dc6339 - (4 days ago) Added Ubuntu version numbers to existing models
| * 957cd6a - (4 days ago) Added models for major Ubuntu versions
|/
*   7b7cfbe - (4 weeks ago) Merge pull request #425 from adean20csc/atftpd (origin/master, origin/HEAD, master)
|\
````

**Comment by jcpowermac** [comment]
@hickey I tested 14.04 - 16.04.  I think there is an issue with GA 16.04.  Not specifically with your model but an issue with install software.  I ran into this [bug](https://bugs.launchpad.net/ubuntu/+source/clock-setup/+bug/1548990) and after I resolved that there was an installation failure.  Unfortunately no real details as to what the problem was.

I am still good for merge... 👍

**Comment by hickey** [comment]
I agree. I just pulled 16.04 yesterday to give it a try and got a chance to get it going this evening. 

I can tell you that it is failing in a similar way to when the net booting was changed in 12.10 (hence the need for these patches). The URL that is being attempted to be used for the live distribution to install from is "/cdromhttp://.....". Clearly either something was broken with this release or another preseed change was made. 

As soon as I find out what the change was, I will update the ubuntu_xenial files and produce another PR. 

Thanks.

**Pull request merged**
